### ISSUE TITLE
router.reLaunch导致缓存的组件失活

### ISSUE THREAD

**Issue by xjh-1996** [ByePastHub/vue-with-keep-alive#1]
复现步骤：
pageA: router.reLaunch({ name: 'pageB' }
pageB: router.push({ name: 'pageC' })
pageC: 物理键返回pageB
此时pageB组件未激活

**Comment by ByePastHub** [comment]
我并没有重现的所说的问题，或许你可以提供一个较为完整的示例
https://stackblitz.com/edit/vitejs-vite-wwvkkz?file=src%2Fviews%2FPage1.vue&terminal=dev

**Comment by xjh-1996** [comment]
@ByePastHub  https://stackblitz.com/edit/vitejs-vite-wvzfa3?file=src%2Fviews%2FPage1.vue
这里可以看到从page3返回后，page2没有触发activated

**Comment by ByePastHub** [comment]
> @ByePastHub https://stackblitz.com/edit/vitejs-vite-wvzfa3?file=src%2Fviews%2FPage1.vue 这里可以看到从page3返回后，page2没有触发activated

vue2.x version: 2.3.2
vue3.x version: 3.3.2
上面版本已修复
