### ISSUE TITLE
typescript支持

### ISSUE THREAD

**Issue by xjh-1996** [ByePastHub/vue-with-keep-alive#3]
请问可以输出一份typescript声明文件吗？👶

**Comment by ByePastHub** [comment]
> 请问可以输出一份typescript声明文件吗？👶

后续我会加上，不过建议你使用[vue-keep](https://github.com/ByePastHub/vue-keep)替换当前的，vue-keep是vue-with-keep-alive升级版。使用起来更加方便，同时也更加完善
